spring :
  #DataSource configuration for the H2 in-memory database
  datasource:
    url: jdbc:h2:mem:superDuperDrive
    username: ThanhVD9
    password: 12345
    driverClassName: org.h2.Driver

  #Configuration for H2 Console
  h2:
    console.enabled: true
    console:
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false

  #Configuration for Thymeleaf template
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8